[package]
name = "nytrs"
version = "0.1.1"
authors = ["Matt Usifer <mattusifer@gmail.com>"]
edition = "2018"

[dependencies]
failure = "^0.1"
reqwest = "^0.9"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
